---
# tasks file for cleanup
- name: Delete "myregistry" Directory Recursivly
  file:
    state: absent
    path: /home/mctux/myregistry

- name: Delete myregistry container
  containers.podman.podman_container:
    name: "myregistry"
    state: absent
