---
# tasks file for cleanup
- name: Delete /home/rocko/4_8_17/myregistry Recursivly
  file:
    state: absent
    path: /home/rocko/4_8_17/myregistry

- name: Delete leftover files and dirs
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - run.sh  
    - images.txt
    - imageContentSourcePolicy.yaml

- name: Delete myregistry container
  containers.podman.podman_container:
    name: "myregistry"
    state: absent

- name: Delete the index images
  containers.podman.podman_image:
    name: "{{ item }}"
    state: absent
    force: yes
  loop:
    - "my-{{index_image}}-index:v1"
    - "registry.redhat.io/redhat/{{index_image}}-index:{{index_image_version}}"
